# Resource for small specification slave pods
apiVersion: v1
kind: Service
metadata:
  name: x86-small-slaves-service
  namespace: jenkins
  labels:
    app: x86-small-slaves
spec:
  ports:
    - port: 80
      name: port-placeholder
  clusterIP: None
  selector:
    app: x86-small-slaves

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: x86-small-slaves
  namespace: jenkins
  labels:
    app: x86-small-slaves
spec:
  serviceName: x86-small-slaves-service
  replicas: 1
  selector:
    matchLabels:
      app: x86-small-slaves
  template:
    metadata:
      labels:
        app: x86-small-slaves
    spec:
      initContainers:
        - name: slave-init
          image: swr.cn-south-1.myhuaweicloud.com/opengauss/jenkins-slave-tools:v1.0.2020032500
          volumeMounts:
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              value: opengauss
            - name: JENKINS_USER_PASSWORD
              value: 110ec45dcf86130cb6f350e5c2ff714d74
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.opengauss.org
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-config
            - name: EXECUTOR_NUMBERS
              value: "1"
            - name: NODE_LABELS
              value: x86 k8s-small
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(JENKINS_AGENT_WORKDIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
      containers:
        - name: jenkins-slave
          image: swr.cn-south-1.myhuaweicloud.com/opengauss/ms_check_slave:v1.0.2020032500
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: x86-small-slaves-pvc
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
            - mountPath: /home/jenkins/share-data
              name: jenkins-share-data
          command:
            - /bin/sh
            - -c
            - |
              export JENKINS_SECRET=`cat /home/jenkins/share-config/node_secret.id`;
              exec jenkins-agent
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              cpu: 2000m
              memory: 3000Mi
          env:
            - name: JENKINS_TUNNEL
              value: jenkins.opengauss.org:50000
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.opengauss.org
      volumes:
        - name: jenkins-share-config
          emptyDir: {}
        - name: jenkins-share-data
          persistentVolumeClaim:
            claimName: x86-small-slaves-share
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: x86-small-slaves-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: "sas"
