---
apiVersion: v1
kind: Service
metadata:
  name: odd-service
  namespace: opengauss-odd
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: odd-deployment
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: opengauss-odd
spec:
  selector:
    k8s-app: oauth2-proxy
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
