resources:
- namespace.yaml
- website-deployment.yaml
- backend-deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml
commonAnnotations:
  email: 747802914@qq.com
  owner: liuyang
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-reproducible
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-reproducible-backend
  newTag: 6f7fabe0405e4325a10a0fea16d1a073c0413ac8
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-reproducible-website
  newTag: 5bfd91be39722c32acf246173ec81c0df310386f
