resources:
- namespace.yaml
- website-deployment.yaml
- backend-deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml
commonAnnotations:
  email: 747802914@qq.com
  owner: liuyang
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-reproducible
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-reproducible-backend
  newTag: 74a6fe88adf60e5804b73aa1e47497c3554a516a
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-reproducible-website
  newTag: aac25ae3a625eb0339d5118571906c1f60e211fd
