---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-reproducible-secret
  namespace: opengauss-reproducible
spec:
  name: opengauss-reproducible-secret
  keysMap:
    host_user:
      path: secrets/data/opengauss/opengauss-reproducible
      key: host_user
    host_password:
      path: secrets/data/opengauss/opengauss-reproducible
      key: host_password