---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: jenkins-oauth-secret
spec:
  name: jenkins-oauth-secret
  keysMap:
    client_id:
      path: secrets/data/infra-common/gitee-applications/opengauss-jenkins
      key: client_id
    client_secret:
      path: secrets/data/infra-common/gitee-applications/opengauss-jenkins
      key: client_secret
    cookie_secret:
      path: secrets/data/infra-common/gitee-applications/opengauss-jenkins
      key: cookie_secret
