resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opengauss/blog
  newTag: v1.0.20220914230445
