resources:
- agentservice.yaml
- config.yaml
- cronjob.yaml
- deployment.yaml
- ingress.yaml
- masterservice.yaml
- namespace.yaml
- oauth-proxy.yaml
- role.yaml
- secrets.yaml
- storage.yaml
commonAnnotations:
  email: 747802914@qq.com
  owner: liuyang
namespace: jenkins
images:
- name: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins
  newTag: 0be18a22a74d58443833698a04a05e18a321f399
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
