---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: jenkins-oauth-secret
  namespace: jenkins
spec:
  name: jenkins-oauth-secret
  keysMap:
    client_id:
      path: secrets/data/opengauss/jenkins
      key: client_id
    client_secret:
      path: secrets/data/opengauss/jenkins
      key: client_secret
    cookie_secret:
      path: secrets/data/opengauss/jenkins
      key: cookie_secret

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-jenkins
  namespace: jenkins
spec:
  name: opengauss-jenkins
  keysMap:
    jenkins-admin-user:
      path: secrets/data/opengauss/jenkins
      key: jenkins-admin-user
    jenkins-admin-password:
      path: secrets/data/opengauss/jenkins
      key: jenkins-admin-password