apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-summary
resources:
- opengauss-summary-deployment.yaml
- opengauss-summary-ingress.yaml
- opengauss-summary-service.yaml
- oauth-proxy.yaml
- namespace.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/summary
  newTag: v1.0.20221230110518