apiVersion: v1
kind: Service
metadata:
  name: opengauss-summary-service
  namespace: opengauss-summary
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: opengauss-summary
  type: ClusterIP
