apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: website-ingress
  namespace: opengauss-usercenter
spec:
  rules:
  - host: id.opengauss.org
    http:
      paths:
      - backend:
          serviceName: website-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - id.opengauss.org
    secretName: website-tls
