apiVersion: v1
kind: ConfigMap
metadata:
  name: websitesvcconfigmap
  namespace: website
data:
  default.conf: |
    server {
        listen 80 ;

        root /usr/share/nginx/html;
        index index.html;
        server_name localhost;

        server_tokens off;
        add_header X-Frame-Options SAMEORIGIN;

        location /zh {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
                error_page   404  /zh/404.html;
        }
        
        location /en { 
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
                error_page   404  /en/404.html;
        } 

        location /cla/ {
                proxy_pass http://bot.opengauss.org:8888/cla;
        }

        location /search/docs {
                proxy_pass https://indextool.opengauss.org/docs;
        }

        location /statistics/ {
                proxy_pass https://www.openeuler.org/api/;
        } 
      
        location /advisoryCVE/ {
                proxy_pass https://api.openeuler.org/cve-manager/;
        }

        location /api-certification/ { 
                proxy_pass https://ccs.opengauss.org/ccs/base/;
        }        

        location = /gitee_back/ {
            break;
            return 200 $request_uri;
            proxy_pass http://meeting-service.meetingserver.svc.cluster.local$request_uri;
        }

        location /calendar/ {
            proxy_pass http://meeting-service.meetingserver.svc.cluster.local/;
        }

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a    404.
                try_files $uri $uri/ =404;
                error_page   404 /zh;
        }
    }
