---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websiteinfo
  namespace: website
  labels:
    app: websiteinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.websiteinfod: semver:~1.0
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: websiteinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: websiteinfo
    spec:
      containers:
      - name: websiteinfod
        image: swr.ap-southeast-1.myhuaweicloud.com/opengauss/website:v1.0.20220616202038
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      volumes:
      - name: configmap-volume
        configMap:
          name: websitesvcconfigmap
