apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-tls
  namespace: website
spec:
  name: website-tls
  keysMap:
    ca.crt:
      path: secrets/data/opengauss/opengauss-website
      key: server.crt
    tls.crt:
      path: secrets/data/opengauss/opengauss-website
      key: server.crt
    tls.key:
      path: secrets/data/opengauss/opengauss-website
      key: server.key