---
apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-configmap
  namespace: download
data:
  default.conf: |
    server {
        listen 80;

        if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})") {
               set $year $1;
               set $month $2;
               set $day $3;
        }
        access_log /dev/stdout main;

        server_name download.opengauss.org;
        location / {
            root   /repo/opengauss;
            fancyindex on;
            fancyindex_exact_size off;
            fancyindex_localtime on;
            autoindex   on;
        }
        location = /favicon.ico {
          log_not_found off;
          access_log off;
        }
    }
  nginx.conf: |-
    user  root;
    worker_processes  auto;

    error_log  /dev/stdout warn;
    pid        /var/run/nginx.pid;

    load_module "/etc/nginx/modules/ngx_http_fancyindex_module.so";

    events {
        worker_connections  1024;
    }

    http {

        # the cidr used for elb cluster
        set_real_ip_from 100.125.0.0/16;
        real_ip_recursive on;
        real_ip_header X-Forwarded-For;

        log_format  main  '$remote_addr'
        '[$time_local] "$request" $status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" $request_filename';

        sendfile        on;
        tcp_nopush      on;

        keepalive_timeout  65;

        #gzip  on;

        server_tokens off;
        include /etc/nginx/conf.d/*.conf;
    }
