apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: indextool-ingress
  namespace: indextool
spec:
  tls:
    - hosts:
        - indextool.opengauss.org
      secretName: indextool-tls
  rules:
    - host: indextool.opengauss.org
      http:
        paths:
        - backend:
            serviceName: indextoolservice
            servicePort: 8080
          path: /