apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: indextool-tls
  namespace: indextool
spec:
  name: indextool-tls
  keysMap:
    ca.crt:
      path: secrets/data/opengauss/opengauss-indextool
      key: server.crt
    tls.crt:
      path: secrets/data/opengauss/opengauss-indextool
      key: server.crt
    tls.key:
      path: secrets/data/opengauss/opengauss-indextool
      key: server.key