# Config indextool service
---

apiVersion: v1
kind: Service
metadata:
  name: indextoolservice
  namespace: indextool
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32123
      name: httpport
  selector:
    app: indextoolinfo
  type: NodePort

