---
apiVersion: v1
kind: Service
metadata:
  name: indextoolservice
  namespace: indextool
spec:
  ports:
  - name: httpport
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: indextoolinfo
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: doc-search-service
  namespace: indextool
spec:
  ports:
  - name: httpport
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: doc-search
  type: ClusterIP

