resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
namespace: opengauss-tryme-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-tryme-website
  newTag: a8191ad4818ca78ebcdb8a1a37a98a3b45986664
