apiVersion: v1
kind: Service
metadata:
  name: post-verification-service
  namespace: opengauss-repo-verify
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 89d9f1e8-f599-4389-b237-9e4c88aa67f8
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  ports:
  - name: http-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: post-verification
  type: LoadBalancer