---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meeting-data-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sas
  volumeMode: Filesystem
