apiVersion: v1
kind: Service
metadata:
  name: meeting-service
spec:
  selector:
    app: meetingserver
    component: web-server
  ports:
    - name: meeting-api-endpoint
      port: 80
      targetPort: 8080
