kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data-vol
  namespace: jenkins
  annotations:
    everest.io/disk-volume-type: GPSSD
spec:
  volumeMode: Filesystem
  accessModes:
  - readWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-disk
  volumeName: pv-evs-jenkins-home