---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opengauss-jenkins
  namespace: jenkins
  labels:
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-master"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opengauss-jenkins-schedule-agents
  namespace: jenkins
  labels:
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-master"
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opengauss-jenkins-schedule-agents
  namespace: jenkins
  labels:
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-master"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opengauss-jenkins-schedule-agents
subjects:
- kind: ServiceAccount
  name: opengauss-jenkins
  namespace: jenkins