apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: opengauss-docs-ingress
  namespace: opengauss-docs
spec:
  rules:
  - host: docs.opengauss.org
    http:
      paths:
      - backend:
          serviceName: opengauss-docs-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - docs.opengauss.org
    secretName: opengauss-docs-tls
