resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- secret.yaml
- ingress.yaml
namespace: moocstudio-opengauss-backend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/moocstudio-opengauss-backend
  newTag: c9755fe384270cdd3bc2b63dd3b047c83a1b788a
