---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-secrets
  namespace: mail
spec:
  name: mailman-secrets
  keysMap:
    hyperkitty_api_key:
      path: secrets/data/mindspore/mail_secrets
      key: hyperkitty_api_key
    mailman_core_password:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_core_password
    mailman_core_user:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_core_user
    secret_key:
      path: secrets/data/mindspore/mail_secrets
      key: secret_key
    postgres_user:
      path: secrets/data/mindspore/mail_secrets
      key: postgres_user
    postgres_password:
      path: secrets/data/mindspore/mail_secrets
      key: postgres_password
    mailman_admin_email:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_admin_email
    exim4_credential:
      path: secrets/data/mindspore/mail_secrets
      key: exim4_credential
    exim4_credential_username:
      path: secrets/data/mindspore/mail_secrets
      key: exim4_credential_splitted_username
    exim4_credential_password:
      path: secrets/data/mindspore/mail_secrets
      key: exim4_credential_splitted_password
    dkim_key:
      path: secrets/data/mindspore/mail_secrets
      key: dkim_key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-cert-secrets
  namespace: mail
spec:
  name: mailman-cert-secrets
  keysMap:
    server_crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    server_key:
      path: secrets/data/mindspore/website-secrets
      key: server.key