resources:
- exim-configmap.yaml
- ingress.yaml
- mailcore.yaml
- mtaservice.yaml
- namespace.yaml
- nginx-config.yaml
- secrets.yaml
- storage.yaml
- suiteservice.yaml
- webservice.yaml
namespace: mail
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-core-new-build
  newTag: 0dea87551fb54b1a2537276bea0d6f9140fa8fc21675394937
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-web-new-build
  newTag: 66c6783525d8dafa60f8646d7a08b60d140f11f61675153074
