resources:
- exim-configmap.yaml
- ingress.yaml
- mailcore.yaml
- mtaservice.yaml
- namespace.yaml
- nginx-config.yaml
- secrets.yaml
- storage.yaml
- suiteservice.yaml
- webservice.yaml
namespace: mail
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
