---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-secrets
  namespace: mail
spec:
  name: mailman-secrets
  keysMap:
    hyperkitty_api_key:
      path: secrets/data/opengauss/mail_secrets
      key: hyperkitty_api_key
    mailman_core_password:
      path: secrets/data/opengauss/mail_secrets
      key: mailman_core_password
    mailman_core_user:
      path: secrets/data/opengauss/mail_secrets
      key: mailman_core_user
    secret_key:
      path: secrets/data/opengauss/mail_secrets
      key: secret_key
    postgres_ip:
      path: secrets/data/opengauss/mail_secrets
      key: postgres_ip
    postgres_url:
      path: secrets/data/opengauss/mail_secrets
      key: postgres_url
    postgres_port:
      path: secrets/data/opengauss/mail_secrets
      key: postgres_port
    postgres_user:
      path: secrets/data/opengauss/mail_secrets
      key: postgres_user
    postgres_password:
      path: secrets/data/opengauss/mail_secrets
      key: postgres_password
    mailman_admin_email:
      path: secrets/data/opengauss/mail_secrets
      key: mailman_admin_email
    exim4_credential:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential
    exim4_credential_splitted_username:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential_splitted_username
    exim4_credential_splitted_password:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential_splitted_password
    exim4_credential_username:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential_splitted_username
    exim4_credential_password:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential_splitted_password
    dkim_key:
      path: secrets/data/opengauss/mail_secrets
      key: dkim_key
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-cert-secrets
  namespace: mail
spec:
  name: mailman-cert-secrets
  keysMap:
    server.crt:
      path: secrets/data/opengauss/mail_secrets
      key: server.crt
    server.key:
      path: secrets/data/opengauss/mail_secrets
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-tls-secrets
  namespace: mail
spec:
  name: mailman-tls-secrets
  keysMap:
    opengauss_org_crt:
      path: secrets/data/opengauss/mail_secrets
      key: opengauss_org_crt
    opengauss_org_key:
      path: secrets/data/opengauss/mail_secrets
      key: opengauss_org_key
