## define the config volume for both mail-core & exim4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-vol
  namespace: mail
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-rw
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailweb-static-vol
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-disk
  volumeMode: Filesystem
